FROM debian:stable-slim

RUN apt-get update

RUN apt-get install --no-install-recommends -y libffi6 python3 python3-pip
RUN adduser --system --shell /bin/bash --group --disabled-password cowrie
COPY cowrie/requirements.txt .

RUN apt-get install --no-install-recommends -y python3-setuptools build-essential libssl-dev libffi-dev python3-dev libsnappy-dev default-libmysqlclient-dev
RUN pip3 install -r requirements.txt

ENV DOCKER=yes

USER cowrie
CMD "/opt/cowrie/bin/cowrie start"
